#!/bin/sh
xrandr \
    --output DP-0 --primary --mode 2560x1440 --rate 164.83 \
    --pos 0x0 --rotate normal \
    --output HDMI-0 --mode 1920x1080 --pos 2560x240 --rotate normal \
    --output DVI-D-0 --off \
    --output DP-1 --off --output DP-2 --off --output DP-3 --off \
    --output DP-4 --off --output DP-5 --off

echo "DP-0" > $MON_CONF
echo "HDMI-0" >> $MON_CONF
