#!/bin/sh
xrandr --output eDP --mode 1920x1080 --pos 0x1440 --rotate normal \
    --output HDMI-A-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal

echo "HDMI-A-0" > $MON_CONF
echo "eDP" >> $MON_CONF
