#! /bin/sh

if [[ "$1" = 0 ]]
then
    # Autostart
    xautolock -time 25 -locker 'i3lock -c 1c1f24' &
    redshift -l 57.01:9.58 &
    # gitwatch ~/repos/vimwiki &
    # setlayout "$DEFAULT_KEYBOARD_LAYOUT"
    setxkbmap -option compose:menu
    startsxhkd
    picom -b &
    bluetoothctl power off &
fi

# configureworkspaces "$1"
# startpolybar

reloadmonitors "$1"

# CONFIG
bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.5
bspc config focused_border_color \#BF616A
bspc config normal_border_color  \#1c1f24
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config directional_focus_tightness low

# WINDOW RULES
bspc config external_rules_command "$HOME/malteos/config/bspwm/external-rules"

bspc rule -a hw-architect-winit desktop=v state=floating
bspc rule -a Steam desktop=w
bspc rule -a Minecraf desktop=v
bspc rule -a Civ5XP desktop=v
bspc rule -a discord desktop=j
bspc rule -a Code desktop=t
bspc rule -a Guitarix desktop=y
bspc rule -a '*:qjackctl' desktop=y
bspc rule -a Zathura state=tiled
bspc rule -a pinentry-qt state=floating
bspc rule -a float state=floating rectangle=1600x900+0+0 center=true
bspc rule -a mpv state=floating rectangle=1600x900+0+0 center=true

steamlib=/home/malte/.local/share/Steam
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')
for game in $mygames; do
    bspc rule -a steam_app_$game desktop=v
done

if [[ "$1" = 1 ]]
then
    sleep 10; amixer -D pipewire sset 'Master' $AUDIO_VOL%
fi
