#! /bin/bash

choice=$(echo "lock
exit
logout
poweroff
reboot" |
    dmenu -i -c -fn 'pixelsize=20' -l 5)

case $choice in
    lock)
        xautolock -locknow;;
    exit)
        bspc quit;;
    logout)
        bspc quit; exit;;
    poweroff)
        sudo poweroff;;
    reboot)
        sudo reboot;;
esac
