#!/bin/bash

options="choose layout
pass
monitor
guitarix
resets
audio"

layouts="wokmok
us intl
voyager
danish"

resets="monitors
workspaces
background
polybar
keyd
rate
fixdimensions
sxhkd
dkletters"

chosen="$(echo "$options" | dmenu -i -ae -c -fn 'pixelsize=20' -l 10)" || exit 1

case "$chosen" in
    "choose layout")
        setlayout dmenu
        setrate
        startsxhkd;;

    "pass")
        alacritty --class float,float -e passmenu ;;

    "monitor")
        selectmon;;

    "guitarix")
        qjackctl &
        guitarix &;;

    "resets")
        chosen="$(echo "$resets" | dmenu -i -ae -c -fn 'pixelsize=20' -l 8)" || exit 1
        case "$chosen" in
            "monitors") reloadmonitors;;
            "workspaces") configureworkspaces;;
            "background") setbg;;
            "polybar") startpolybar;;
            "keyd") alacritty --class float,float -e sudo systemctl restart keyd;;
            "rate") setrate;;
            "fixdimensions") fixdimensions;;
            "sxhkd") startsxhkd;;
            "dkletters") setxkbmap -option compose:menu;;
        esac;;

    "audio")
        audio;;
esac
