#!/bin/bash

options="choose layout
pass
monitor
guitarix
resets
audio"

layouts="wokmok
us intl
voyager
danish"

resets="monitors
workspaces
background
polybar
rate
dimensions
sxhkd"

chosen="$(echo "$options" | dmenu -i -ae -c -fn 'pixelsize=20' -l 10)" || exit 1

case "$chosen" in
    "choose layout")
        setlayout dmenu
        setrate
        startsxhkd;;

    "pass")
        passmenu &;;

    "monitor")
        selectmon;;

    "guitarix")
        qjackctl &
        guitarix &;;

    "resets")
        chosen="$(echo "$resets" | dmenu -i -ae -c -fn 'pixelsize=20' -l 7)" || exit 1
        case "$chosen" in
            "monitors") reloadmonitors;;
            "workspaces") configureworkspaces;;
            "background") setbg;;
            "polybar") startpolybar;;
            "rate") setrate;;
            "dimensions") fixdimensions;;
            "sxhkd") startsxhkd;;
        esac;;

    "audio")
        audio;;
esac
