#!/bin/bash

DIR="0"
while getopts ":d" opt; do
    case $opt in
        d)
            DIR="1";;
    esac
done

file () {
    alacritty --class float,float -e of "$@"
    bash ~/.cache/ofcmd
    # cmd=`cat ~/.cache/ofcmd`
    # alacritty -e nvim -c "cd /home/malte/dotfiles" /home/malte/dotfiles/scripts/godir
    # $cmd &
}

dir () {
    alacritty --class float,float -e of "$@" -d
    path=`cat ~/.cache/ofcmd`
    [ -n "$path" ] && alacritty --working-directory "$path"
}

if [ "$DIR" -eq "0" ]; then
    file "$@"
else
    dir "$@"
fi
