#!/bin/bash

if [[ $# -eq 1 ]]; then
  if [[ -f "$1" ]]; then
    path=$(dirname $1)
  else
    path=$1
  fi
  _root_dir="$(git -C $path rev-parse --show-toplevel 2>/dev/null)"
  if [[ $? -gt 0 ]]; then
    echo $path
  else 
    echo $_root_dir
  fi
else
  _root_dir="$(git rev-parse --show-toplevel 2>/dev/null)"
  if [[ $? -gt 0 ]]; then
    pwd
  else 
    echo $_root_dir
  fi
fi

