#!/bin/sh

MON1="a s r t v"
MON2="u y f w d j"
MON3="x o"
readarray -t MONITORS < $MON_CONF
# xrandr --output ${MONITORS[0]} --primary

currdesk="a"
[[ $1 -ne 0 ]] && currdesk=`bspc query -D -d focused`

ALLMONS="$MON1 $MON2 $MON3"
[[ "$1" = 0 ]] && bspc monitor ${MONITORS[0]} -d $ALLMONS

case ${#MONITORS[@]} in
    1) 
        MONCOMB="$MON1 $MON2 $MON3"
        MONLIST=($MONCOMB)
        for d in "${MONLIST[@]}"
        do
            bspc desktop -f "$d"
            bspc desktop -m ${MONITORS[0]}
        done
        bspc desktop -f $currdesk;;
    2)
        MONLIST=($MON1)
        for d in "${MONLIST[@]}"
        do
            bspc desktop -f "$d"
            bspc desktop -m "${MONITORS[0]}"
        done
        MONCOMB="$MON2 $MON3"
        MONLIST=($MONCOMB)
        for d in "${MONLIST[@]}"
        do
            bspc desktop -f "$d"
            bspc desktop -m "${MONITORS[1]}"
        done
        bspc desktop -f $currdesk;;
    3)
        MONLIST=($MON1)
        for d in "${MONLIST[@]}"
        do
            bspc desktop -f "$d"
            bspc desktop -m ${MONITORS[0]}
        done
        MONLIST=($MON2)
        for d in "${MONLIST[@]}"
        do
            bspc desktop -f "$d"
            bspc desktop -m ${MONITORS[1]}
        done
        MONLIST=($MON3)
        for d in "${MONLIST[@]}"
        do
            bspc desktop -f "$d"
            bspc desktop -m ${MONITORS[2]}
        done
        bspc desktop -f $currdesk;;
esac

