#!/bin/sh

killall sxhkd

chosen=$(cat "$HOME/.cache/keyboard")
case "$chosen" in
    "wokmok" | "wokmok_dk" | "wokmok_us" | "layer5_wokmok_dk" | "layer5_wokmok_us" | "custom")
        cat ~/malteos/config/sxhkd/{base,wokmok} > ~/.config/sxhkd/sxhkdrc;;
    "us" | "dk" | "layer5_us" | "layer5_dk")
        cat ~/malteos/config/sxhkd/{base,qwerty} > ~/.config/sxhkd/sxhkdrc;;
esac

pgrep -x sxhkd > /dev/null || sxhkd &
